#!/usr/bin/env bash

function fgrep()
{
    find . -name .repo -prune -o -name .git -prune -o -type f \( -name '*.c' -o -name '*.cc' -o -name '*.cpp' -o -name '*.h' \) -print0 | xargs -0 grep --color -n "$@"
}

function hgrep()
{
    find . -name .repo -prune -o -name .git -prune -o -type f \( -name '*.h' \) -print0 | xargs -0 grep --color -n "$@"
}

function jgrep()
{
    find . -name .repo -prune -o -name .git -prune -o -name *.min.* -prune -o -type f \( -name '*.js' \) -print0 | xargs -0 grep --color -n "$@"
}

function buildtag()
{
    #find . -type f -iname "*.[ch]" | xargs etags -a
	ctags -R
}

function fps()
{
	ps aux | grep $@ | grep -v "grep" | grep $@
}

function nfind()
{
    find . -name $@
}

function calc()
{
    if [ $2 = "+" ]
    then
        echo $(expr $1 + $3)
    elif [ $2 = "-" ]
    then
        echo $(expr $1 - $3)
    elif [ $2 = "x" ]
    then
        echo $(expr $1 \* $3)
    elif [ $2 = '/' ]
    then
        echo $(expr $1 / $3)
    else 
        echo 'parse error'
    fi
}

function cds()
{
	t=$(ls -al | grep -i -E $1 | head -n 1 | sed -E "s/^.{10}\s+[0-9]+\s+\w+\s+\w+\s+[0-9]+\s+.+\s+([0-9]+|[0-9]{2}:[0-9]{2})\s//g")
	if [ -n "$t" ]; then
		echo $t
		cd $t
	else
		echo "No match "$1
	fi
}

function int2hex()
{
    printf '0x%x\n' $1
}

function hex2int()
{
    echo $((0x$1))
}

function mncom()
{
	YEAR=$(date +%Y)
	MOUNTH=$(date +%m)
	DAY=$(date +%d)
	HOUR=$(date +%H)
	MIN=$(date +%M)
	SEC=$(date +%S)

	sudo minicom -c on -s -C "/home/minicom_log/$YEAR$MOUNTH$DAY-$HOUR$MIN$SEC.log"
}

function DirDiff()
{
	DIR1=$(printf '%q' "$1"); shift
	DIR2=$(printf '%q' "$1"); shift
	vi $@ -c "DirDiff $DIR1 $DIR2"
}

alias l='ls -alh'
alias ll='ls -lh'

alias c='cd ~/proj/c'
alias py='cd ~/proj/python/'
alias proj='cd ~/proj'
alias pcap='cd ~/proj/packet/pcapremote'
alias wave2='cd ~/proj/eap_5.0.4_kt_entAP_5.1.2'
alias shell='cd ~/proj/shell'
alias react='cd ~/proj/node/react'
alias web='cd ~/proj/web'
alias down='cd ~/Download'
#alias tftp='cd /tmp/symbolic/tftp'
alias gusb='ls -al /dev/ttyUSB*'
alias vimhis='cd ~/.vimhistory'

#kt_gww2
alias 22='cd /home/youn/proj/KT_GWW2_QCA_SDK_6.1.0_CS/'
alias 222='cd /home/youn/proj/KT_GWW2_QCA_SDK_6.1.0_CS/build_dir/target-arm_cortex-a7_uClibc-1.0.14_eabi'
alias dvpkg='cd /home/youn/proj/KT_GWW2_QCA_SDK_6.1.0_CS/build_dir/target-arm_cortex-a7_uClibc-1.0.14_eabi/dv_pkg/'
alias hostapd='cd /home/youn/proj/KT_GWW2_QCA_SDK_6.1.0_CS/build_dir/target-arm_cortex-a7_uClibc-1.0.14_eabi/qca-hostap-default/qca-hostap-g'
alias ktwebf='cd /home/youn/proj/KT_GWW2_QCA_SDK_6.1.0_CS/davo/feeds/webui/kt_web_light/files/web_src'
alias ktwebb='cd /home/youn/proj/KT_GWW2_QCA_SDK_6.1.0_CS/build_dir/target-arm_cortex-a7_uClibc-1.0.14_eabi/dv_pkg/kt_webserver'
alias cwmpClient='cd /home/youn/proj/KT_GWW2_QCA_SDK_6.1.0_CS/build_dir/target-arm_cortex-a7_uClibc-1.0.14_eabi/dv_pkg/cwmpsslClient'

#11ax
alias 11ax='cd /home/youn/proj/11AX_QCA_SDK_10.0_CS_P2_ENT'

export CMAKE_LIBRARY_PATH=$CMAKE_LIBRARY_PATH:$HOME/caffe2/third_party/nccl/build/lib
# If not running interactively, don't do anything
case $- in
  *i*) ;;
    *) return;;
esac

# Path to the bash it configuration
export BASH_IT="/home/youn/bash-it"

# Lock and Load a custom theme file.
# Leave empty to disable theming.
# location /.bash_it/themes/
# export BASH_IT_THEME='sexy'
export BASH_IT_THEME='sexy-rpg'
#export BASH_IT_THEME='powerline-multiline'
#export BASH_IT_THEME='doubletime'

# (Advanced): Change this to the name of your remote repo if you
# cloned bash-it with a remote other than origin such as `bash-it`.
# export BASH_IT_REMOTE='bash-it'

# Your place for hosting Git repos. I use this for private repos.
export GIT_HOSTING='mobbing@github.com'

# Don't check mail when opening terminal.
unset MAILCHECK

export GIT_DISCOVERY_ACROSS_FILESYSTEM=1

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Set Xterm/screen/Tmux title with only a short hostname.
# Uncomment this (or set SHORT_HOSTNAME to something else),
# Will otherwise fall back on $HOSTNAME.
#export SHORT_HOSTNAME=$(hostname -s)

# Set Xterm/screen/Tmux title with only a short username.
# Uncomment this (or set SHORT_USER to something else),
# Will otherwise fall back on $USER.
#export SHORT_USER=${USER:0:8}

# Set Xterm/screen/Tmux title with shortened command and directory.
# Uncomment this to set.
#export SHORT_TERM_LINE=true

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/djl/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# (Advanced): Uncomment this to make Bash-it reload itself automatically
# after enabling or disabling aliases, plugins, and completions.
# export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1

# Uncomment this to make Bash-it create alias reload.
# export BASH_IT_RELOAD_LEGACY=1

# Load Bash It
source ~/bash-it/bash_it.sh
